import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";
import Footer from "./components/Footer";
import { ScrollProvider } from "./context/ScrollContext";


const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ScrollProvider>
          <div className="sticky top-0 z-50">

            <Navbar />

          </div>
          {children}
          <Footer />
        </ScrollProvider>
      </body>
    </html>
  );
}